common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name='common/login.html'), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('', base_views.index, name="index"),
    path('common/', include('common.urls')),
]

pybo/urls.py
from django.urls import path
from .views import question_views,base_views,answer_views

app_name = 'pybo'

urlpatterns = [
    path("", base_views.index, name="index"),
    path("<int:question_id>/", base_views.detail, name="detail"),
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
]

common/models.py
from django.db import models

# Create your models here.

pybo/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

pybo/forms.py
from django import forms
from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer  # 사용할 모델
        fields = ['content']  # QuestionForm에서 사용할 Question 모델의 속성

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer


@login_required(login_url='common:login')
def answer_create(request: WSGIRequest, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()  # 수정일시 저장
            answer.save()
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)
    answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/views/base_views.py
from django.core.handlers.wsgi import WSGIRequest
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from ..models import Question


def index(request: WSGIRequest) -> render:
    page = request.GET.get('page', '1')  # 페이지
    question_list = Question.objects.order_by('-create_date')
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, 'pybo/question_list.html', context)


def detail(request: WSGIRequest, question_id) -> render:
    question = get_object_or_404(Question, pk=question_id)
    anwser_list = question.answer_set.all()
    context = {'question': question, "anwser_list": anwser_list}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question


@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            # commit = False로 create_date속성이 입력안돼도 Question객체를 반환함
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<div class="navigator">
    <a href="{% url 'pybo:index' %}"><h1>Pybo</h1></a>
    {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
    {% else %}
        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
    {% endif %}
    {% if not user.is_authenticated %}
        <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
    {% endif %}
</div>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/common/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}
    <!-- 답변 수정-->
    <div class="container my-3">
        <form method="post">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="mb-3">
                <label for="content" class="form-label">답변내용</label>
                <textarea class="form-control" name="content" id="content"
                          rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">저장하기</button>
        </form>
    </div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}
    <!-- message 표시 -->
    {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
            {% for message in messages %}
                <strong>{{ message.tags }}</strong>
                <ul>
                    <li>{{ message.message }}</li>
                </ul>
            {% endfor %}
        </div>
    {% endif %}
    <h1>{{ question.subject }}</h1>
    <div class="mb-2">{{ question.author.username }}</div>
    <div>{{ question.create_date }}</div>
    <div>
        {{ question.content }}
    </div>
    <div class="my-3">
        {% if request.user == question.author %}
            <a href="{% url 'pybo:question_modify' question.id %}"
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="{% url 'pybo:question_delete' question.id %}">삭제</a>
        {% endif %}
    </div>
    {% if anwser_list %}
        <h5>{{ anwser_list.count }}만큼 답변이 있습니다.</h5>
        <ul>
            {% for anwser in anwser_list %}
                <div class="list">
                    <li class="page-link">{{ anwser.content }}</li>
                    <div class="page-link">{{ anwser.author }}</div>
                    <div class="page-link">{{ anwser.create_date }}</div>
                    {% if request.user == anwser.author %}
                        <a href="{% url 'pybo:answer_modify' anwser.id %}" class="page-link">수정</a>
                        <a href="{% url 'pybo:answer_delete' anwser.id %}" class="page-link">삭제</a>
                    {% endif %}
                </div>
            {% endfor %}
        </ul>
    {% endif %}
    <form action="{% url 'pybo:answer_create' question.id %}" method="post">
        {% csrf_token %}
        <textarea {% if not user.is_authenticated %}disabled{% endif %} name="content" id="content"
                  rows="10"></textarea>
        <input type="submit" value="답변등록">
    </form>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h5 class="my-3 border-bottom pb-2">질문등록</h5>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">저장하기</button>
        </form>
    </div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
    {% if question_list %}
        <ul class="NoMarginPadding">
            {% for question in question_list %}
                <div class="list">
                    <div class="index">{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</div>
                    <li><a class="index"
                           href="{% url "pybo:detail" question_id=question.id %}">{{ question.subject }}</a></li>
                    {% if question.answer_set.count > 0 %}
                        <div class="index">{{ question.answer_set.count }}</div>
                    {% endif %}
                    <div class="index">{{ question.author }}</div>
                </div>
            {% endfor %}
        </ul>
    {% else %}
        <p>질문이 없습니다.</p>
    {% endif %}
    <!-- 페이징처리 시작 -->
    <ul class="NoMarginPadding">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
        {% else %}
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
            {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
                {% if page_number == question_list.number %}
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                {% else %}
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                {% endif %}
            {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        {% else %}
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
{% endblock %}